version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "5173:5173"
    volumes:
      # Đồng bộ code từ máy tính (máy host) vào trong container để code có thể Hot-reload
      - .:/app
      # Giữ node_modules ẩn bên trong container, không tràn ra Windows của bạn
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Giúp tính năng tự động reload hoạt động tốt trên Windows