version: '3.8'

services:
  webapp:
    build: .
    ports:
      - "5173:5173"
    volumes:
      # Đồng bộ code từ máy host vào container cho Hot-reload
      - .:/app
      # Giữ node_modules ẩn trong container
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true